name: Production

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-upload:
    name: WebGL Build and Upload to R2
    runs-on: ubuntu-latest
    outputs:
      object_key: ${{ steps.r2-upload.outputs.object_key }}
      object_locations: ${{ steps.r2-upload.outputs.object_locations }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Unity Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      - name: Check build
        run: |
          tree build

      - name: Upload to R2 - Use S3 API
        uses: shallwefootball/upload-s3-action@v1.3.3
        id: r2-upload
        with:
          aws_key_id: ${{ secrets.R2_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.R2_SECRET_KEY }}
          aws_bucket: demo-argus-web-player
          source_dir: ./build/WebGL/WebGL/Build
          destination_dir: ${{ github.sha }}
          endpoint: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com

      - name: Show Uploaded Object Locations
        run: |
          echo "object_key: ${{ steps.r2-upload.outputs.object_key }}"
          echo "object_locations: ${{ steps.r2-upload.outputs.object_locations }}"
