name: Production

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-upload:
    name: WebGL Build and Upload to R2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Cache Library
      #   uses: actions/cache@v3
      #   with:
      #     path: Library
      #     key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
      #     restore-keys: |
      #       Library-

      # - name: Unity Build
      #   uses: game-ci/unity-builder@v4
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #   with:
      #     targetPlatform: WebGL

      - name: Check build
        run: |
          tree build

      - name: Upload to R2 and update registry
        uses: ryanditjia/demo-actions@registry
        with:
          game-name: demoargusid
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key: ${{ secrets.R2_ACCESS_KEY }}
          r2-secret-key: ${{ secrets.R2_SECRET_KEY }}
          r2-bucket: demo-argus-web-player
          r2-custom-domain: https://cdn.ryanditjia.com
          r2-destination-dir: ${{ github.sha }}
          web-player-env: production
          webgl-build-dir: ./build/WebGL/WebGL/Build
          web-player-repo-pat: ${{ secrets.WEB_PLAYER_REPO_PAT }}
